### ISSUE TITLE
error occurs when set "jsc.parser.syntax" to "typescript"

### ISSUE THREAD

**Issue by not3** [iheyunfei/vite-on-swc#1]
my config:
```
jsc: {
  parser: {
    syntax: "typescript",
    tsx: true,
  },
  target: "es2022",
}
```
error in the console:
> [vite-plugin-swc-react] Failed to deserialize argument at `2` as swc::config::Options
> JSON: {"filename":"C:/Users/not3/workspace/study/react-study/node_modules/.pnpm/registry.npmmirror.com+react@17.0.2/node_modules/react/jsx-runtime.js","jsc":{"target":"es2022","parser":{"syntax":"typescript","jsx":false,"tsx":true},"transform":{"react":{"development":false,"runtime":"automatic","refresh":true}}}}
> 
> Caused by:
>     unknown field `jsx`, expected one of `tsx`, `decorators`, `dynamicImport`, `importAssertions` at line 1 column 308

**Comment by hyfdev** [comment]
The error means the option you are passing to SWC is conflicted with the plugin default SWC options.

You don't need to specify typescript parser, the plugin already does it.

https://github.com/iheyunfei/vite-on-swc/blob/3e164d30ba6ef1238185c08bacf0f75eeb34ec71/packages/react/src/index.ts#L70-L88

for `.js` file, the plugin will use 

https://github.com/iheyunfei/vite-on-swc/blob/3e164d30ba6ef1238185c08bacf0f75eeb34ec71/packages/react/src/index.ts#L77-L80

And they are incompatible with 
```
{
    syntax: "typescript",
    tsx: true,
}
```

The error message explains why,

`unknown field jsx, expected one of tsx, decorators, dynamicImport, importAssertions`
